"""East IR (Intermediate Representation) module.

Provides node definitions for representing East programs as an AST.
"""

from east.ir.nodes import (
    IR,
    As,
    Assign,
    Block,
    Break,
    Builtin,
    Call,
    Continue,
    Error,
    ForArray,
    ForDict,
    ForSet,
    Function,
    GetField,
    IfElse,
    Let,
    Location,
    Match,
    MatchCase,
    NewArray,
    NewDict,
    NewSet,
    Platform,
    Return,
    StructNode,
    TryCatch,
    UnwrapRecursive,
    Value,
    Variable,
    VariantNode,
    While,
    WrapRecursive,
)

__all__ = [
    "IR",
    "Location",
    "Value",
    "Variable",
    "Block",
    "IfElse",
    "While",
    "Break",
    "Continue",
    "Return",
    "Let",
    "Assign",
    "NewArray",
    "NewSet",
    "NewDict",
    "ForArray",
    "ForSet",
    "ForDict",
    "StructNode",
    "GetField",
    "VariantNode",
    "MatchCase",
    "Match",
    "Function",
    "Call",
    "Platform",
    "Builtin",
    "Error",
    "TryCatch",
    "As",
    "UnwrapRecursive",
    "WrapRecursive",
]
